package defpackage;

import kotlin.jvm.internal.Ref;

/* renamed from: ku5  reason: default package */
public final class ku5 implements ds5 {
    public final /* synthetic */ Ref.IntRef a;
    public final /* synthetic */ int b;
    public final /* synthetic */ ds5 c;
    public final /* synthetic */ Object o;

    public ku5(Ref.IntRef intRef, int i, ds5 ds5, Object obj) {
        this.a = intRef;
        this.b = i;
        this.c = ds5;
        this.o = obj;
    }

    /* JADX WARNING: Removed duplicated region for block: B:14:0x0038  */
    /* JADX WARNING: Removed duplicated region for block: B:8:0x0024  */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final java.lang.Object a(java.lang.Object r7, kotlin.coroutines.Continuation r8) {
        /*
            r6 = this;
            boolean r0 = r8 instanceof defpackage.ju5
            if (r0 == 0) goto L_0x0013
            r0 = r8
            ju5 r0 = (defpackage.ju5) r0
            int r1 = r0.c
            r2 = -2147483648(0xffffffff80000000, float:-0.0)
            r3 = r1 & r2
            if (r3 == 0) goto L_0x0013
            int r1 = r1 - r2
            r0.c = r1
            goto L_0x0018
        L_0x0013:
            ju5 r0 = new ju5
            r0.<init>(r6, r8)
        L_0x0018:
            java.lang.Object r8 = r0.a
            java.lang.Object r1 = kotlin.coroutines.intrinsics.IntrinsicsKt.getCOROUTINE_SUSPENDED()
            int r2 = r0.c
            r3 = 2
            r4 = 1
            if (r2 == 0) goto L_0x0038
            if (r2 == r4) goto L_0x0034
            if (r2 != r3) goto L_0x002c
            kotlin.ResultKt.throwOnFailure(r8)
            goto L_0x005f
        L_0x002c:
            java.lang.IllegalStateException r6 = new java.lang.IllegalStateException
            java.lang.String r7 = "call to 'resume' before 'invoke' with coroutine"
            r6.<init>(r7)
            throw r6
        L_0x0034:
            kotlin.ResultKt.throwOnFailure(r8)
            goto L_0x0051
        L_0x0038:
            kotlin.ResultKt.throwOnFailure(r8)
            kotlin.jvm.internal.Ref$IntRef r8 = r6.a
            int r2 = r8.element
            int r2 = r2 + r4
            r8.element = r2
            int r8 = r6.b
            ds5 r5 = r6.c
            if (r2 >= r8) goto L_0x0054
            r0.c = r4
            java.lang.Object r6 = r5.a(r7, r0)
            if (r6 != r1) goto L_0x0051
            return r1
        L_0x0051:
            kotlin.Unit r6 = kotlin.Unit.INSTANCE
            return r6
        L_0x0054:
            r0.c = r3
            java.lang.Object r6 = r6.o
            java.lang.Object r6 = defpackage.qu5.a(r5, r7, r6, r0)
            if (r6 != r1) goto L_0x005f
            return r1
        L_0x005f:
            kotlin.Unit r6 = kotlin.Unit.INSTANCE
            return r6
        */
        throw new UnsupportedOperationException("Method not decompiled: defpackage.ku5.a(java.lang.Object, kotlin.coroutines.Continuation):java.lang.Object");
    }
}
